Tasks
danil12072012/arrays-part-2 pull request #1
Opened 2023-01-25 17:58 UTC by danil12072012

2023-01-25 18:10 UTC, alekseykoshelev requested changes

2023-01-25 18:10 UTC, alekseykoshelev commented on src/Main.java
> +            if (index == 0) {
Не совсем понял зачем эта проверка, ведь код внутри нее такой же, как в цикле. Если ты таким образом хочешь остановить цикл, то этого делать не нужно, цикл сам остановится по условию во второй секции `for`
Вот оно `index >= 0 `

2023-01-25 18:10 UTC, alekseykoshelev commented on src/Main.java
> +            if (minWastes > arr[i]) {
Максимум и минимум можно найти за один проход по циклу. Также лучше изначальное значение взять как первый элемент массива, иначе программа может неправильно работать на других исходных данных.

2023-01-25 18:10 UTC, alekseykoshelev commented on src/Main.java
> +        double average = sum / 30;
Тут нужно сделать явный каст в double. Иначе будет целочисленное деление и дробная часть отбросится. Также лучше вместо 30 использовать длину массива `arr.length`

2023-01-27 13:46 UTC, danil12072012 commented on src/Main.java
> +        double average = sum / 30;
Добрый день. Не совсем поняла на счет каста.

2023-01-28 07:33 UTC, closed without merging